# .streamlit/secrets.toml
# 這是你管理員頁面的密碼，請自己設定
admin_password = "adminadmin"

# 以下是從 Google JSON 憑證檔案中複製過來的內容
[gcp_service_account]
type = "service_account"
project_id = "saveguppy"
private_key_id = "1606b774d105f49aac700f27bcf796db118e2426"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDPAqSqXGiKlxpS
hKjkCF0ayx2qv6Awp+j8BCXzeSgE3Dl1GrcgNKx662CvTNzFb5YoRXma9qH8IBs3
MIp7TyzpGIH6KovNy5POQlwAc534laTVl9/O/NEefv9kGSMUCNnkVaF9j+ONNCNe
KH8f96MN9/FVuajeaTK1nJ1vmwE5ppDiSHuyEfAZx4bBhHRmyATT8YewpxDbd/Ed
+F2ubdx1sSvzE4l91CSsOmdT2XVidjPtaN2ZhdGtqtaX6Kc7/m3fuXJC25KiVxEJ
PuJtgGF1j+G9lDEiMDRr24JrxbwQMGyGY5JNHmiWtUuhAeupPLX9zZV58rK3OuW1
i8BfmpsbAgMBAAECggEAVWHatyWsPNV8FuL+oidM95slXmLxWIA5GZFAcf7b4b1P
uZxOQetX5M8mrsc+G/UdcvjM4nytbUd00jukMp4CgRYJrjxUM4qvKRi3x7voQTq/
pRWiS0Z9nl11Sz0O+dl4vbQQCrEJgxkpKVH8tRu31jAZC2mrXCj5sGyrhvfg9nyd
wyL2DqybPiS3kEQmfOHB4H0ZpsB87iGsGoThwKEGpbqnNOrfxu43BcuYHWo9Fdco
8BV+bYENv7nx82cRcdXbr1w9wdKHR2gInXf9wu1l1WNDTuBN/vaoEqCJiFHeO6vn
7JdSPWySEvuEuz2+qAa02aSRmrwzR8HL6rT0rZTcqQKBgQD37Xz1pIQjYk2/YgqM
Yi3KIaCB+To1L4IAJjVskJnpNKmX/Kx5qin34Eaa44wfQ0paPmjl9W8nbfBqsyXK
uYBOcyZxKl4naDJDkhScsbKo+8OGZdZ22qExZBz+9+yUTQPZ9tIDyqiAkpUsgsrv
VTveA+ZlZBxCA9w9Ogl329+a7wKBgQDVwBppdvIt71MCR8FJ4w4kcDPQS1Ehk/AC
rREjWm608JLt2iQ7CwVBF5QqTUHramm25U9JzthBTgqLvW334XYHqQkJDOUrHJoa
99sAUJhFULHmGGVZYhk8Ker3jddentpfF8NYYzMr8/j0LjmelKy1PBRoW1W3MNhZ
XDgf7/lylQKBgFMTOPP2lHBm2DZw6f+nelFK0th/6cirCTwqKYgLfJ+uvU6rXB3
Hj6ta3g4Wr4WUmz7+JeQ0irBgw6y0cKsXuYCiGRWMtLlswdftqikIMfGX1HUn2w
9KJgMXceDCAFTm0Sz3yFw8CRXXr0uJtJrC3QkLsYuH9GW94IPHP1MQ/xAoGBAJpm
ha2hChc8RQ3kny6sIM8ZbZQMk7JZlomYUkTjUgzJqpi9dmZf84+tZI2Z+QAAghRn
V/rMuyNWKDAAyarA5e1qoOg0tGWL55WLbFqx3QxU2eyHus3yGqBm9x+TCfuDa+I8
3BLAtXoOZcqciWqPoqHXoDYxo50MX3tNLg2D3wBxAoGBAKgNQByf4NmVonOPdnTN
eb3oz8PhCv+8sqHJOxEkf/0Kf0PeZPmy/6Yg5owYqm/i/zQtaPrEzsckwHAMA7y4
x0wkaJNGD0ITLkSPEd2Bt2ldc1i4JpwBz7vXVqhKh90yUsAiGGG33Zwh9fkypHsN
GnITGDl6BEcqAMuBNBDupD5K
-----END PRIVATE KEY-----"""
client_email = "streamlit-gsheets-app@saveguppy.iam.gserviceaccount.com"
client_id = "100170630479860650416"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-gsheets-app%40saveguppy.iam.gserviceaccount.com"
universe_domain = "googleapis.com"